version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: go_restapi_gin
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306

  api:
    build: .
    restart: always
    ports:
      - 8888:8000
      - 9999:8081
    depends_on:
      - db